apiVersion: v1
kind: Pod
metadata:
  name: pod-storage-01
spec:
  containers:
    - name: test
      image: rkalluru/learnk8s:rhel-bare
      volumeMounts:
        - name: empty-dir
          mountPath: /opt
    - name: nginx
      image: ngnix
      volumeMounts:
        - name: empty-dir
          mountPath: /usr/share/ngnix/html
  volumes:
    - name: empty-dir
      emptyDir: {}
